### ISSUE TITLE
[compare.py] The compare tool is too verbose by default!!

### ISSUE THREAD

**Issue by clementval** [eth-cscs/serialbox2#153]
`compare.py` is displaying too many information by default that we do not care about. 

In this example, the field data match and just one meta-data differ. But the `-w` option is passed then we should not have all these useless lines in the output. 

```
[ RUN      ] mo_model_domain__p_patch(1)%cells%dist_io_data%redistrib_pattern%send_startidx
  Field meta-info mismatch: meta-info
    Expected:
      __bytesperelement: 4
      __elementtype: int
      __iminushalosize: 1
      __iplushalosize: 1
      __isize: 1
      __jminushalosize: 0
      __jplushalosize: 0
      __jsize: 0
      __kminushalosize: 0
      __kplushalosize: 0
      __ksize: 0
      __lminushalosize: 0
      __lplushalosize: 0
      __lsize: 0
      __name: mo_model_domain__p_patch(1)%cells%dist_io_data%redistrib_pattern%send_startidx
      __rank: 1
      ftg:loc: 65E6950
      ftg:registered_only: False

    Actual:
      __bytesperelement: 4
      __elementtype: int
      __iminushalosize: 1
      __iplushalosize: 1
      __isize: 1
      __jminushalosize: 0
      __jplushalosize: 0
      __jsize: 0
      __kminushalosize: 0
      __kplushalosize: 0
      __ksize: 0
      __lminushalosize: 0
      __lplushalosize: 0
      __lsize: 0
      __name: mo_model_domain__p_patch(1)%cells%dist_io_data%redistrib_pattern%send_startidx
      __rank: 1
      ftg:loc: 2459180
      ftg:registered_only: False
```
